apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: shuasd/places-backend:8210192ee033fd5b170f505cf7138d3567ac21ea
          env:
            - name: DATASOURCES_DEFAULT_URL
              value: "jdbc:postgresql://db:5432/placesdb"
            - name: DATASOURCES_DEFAULT_USERNAME
              value: "placesdbadmin"
            - name: DATASOURCES_DEFAULT_PASSWORD
              value: "placesdbadminpassword"
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "200m"
            limits:
              cpu: "500m"
