apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: shuasd/places-frontend:149683df9bd94e25c7480cb0e0931ec02bf400ff
          ports:
            - containerPort: 80
