apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: shuasd/places-frontend:8210192ee033fd5b170f505cf7138d3567ac21ea
          ports:
            - containerPort: 80
