services:

  db:
    image: shuasd/places-db:latest
    environment:
      POSTGRES_DB: placesdb
      POSTGRES_USER: placesdbadmin
      POSTGRES_PASSWORD: placesdbadminpassword
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U placesdbadmin -d placesdb"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    image: shuasd/places-backend:latest
    ports:
      - "8080:8080"
    environment:
      DATASOURCES_DEFAULT_URL: jdbc:postgresql://db:5432/placesdb
      DATASOURCES_DEFAULT_USERNAME: placesdbadmin
      DATASOURCES_DEFAULT_PASSWORD: placesdbadminpassword
    depends_on:
      db:
        condition: service_healthy

  frontend:
    image: shuasd/places-frontend:latest
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  pgdata:
